export const PRODDUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODDUCT_LIST_SUCCESS = 'PRODDUCT_LIST_SUCCESS';
export const PRODDUCT_LIST_FAIL = 'PRODDUCT_LIST_FAIL';

export const PRODDUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODDUCT_DETAILS_SUCCESS = 'PRODDUCT_DETAILS_SUCCESS';
export const PRODDUCT_DETAILS_FAIL = 'PRODDUCT_DETAILS_FAIL';
